# Override DB connection for K8s Service DNS
spring.datasource.url=jdbc:postgresql://postgres.che-kube-admin-devspaces-ownaw0.svc.cluster.local:5432/fooddb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


# Optional: Disable 'always' init mode in K8s to prevent overwriting existing data on pod restart
spring.sql.init.mode=never

server.port=8080


# JPA (Java Persistence API) Configuration
# 'update' will create the schema if it doesn't exist, or update it if it has changed.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Data Source Initialization
# This ensures that data.sql is always run on startup to populate the database.
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true